### PR TITLE
Add react-dom to peerDependencies

### PR DESCRIPTION
**Pull request by denkristoffer**

### CODE REVIEW

**Comment by theKashey** [comment]
Hey! Why would one need this?
React-dom is used by underlaying library - react-locky, and listed as it's peer deps.

**Comment by denkristoffer** [comment]
Hey, you're right! Sorry about that. I added it because I was trying to compare `react-scroll-locky` to other alternatives on bundlephobia, which complains about a missing `react-dom` dependency: https://bundlephobia.com/result?p=react-scroll-locky

The issue must be somewhere with how that site handles the dependencies then 🙂

**Comment by theKashey** [comment]
actually you were right - I have to specify peer dependencies of my dependencies, or they will become my dependencies, not peer dependencies.
That's is not a problem for library itself, but all "package analyzers" will add react-dom to the package size :)

**Comment by theKashey** [comment]
🔥https://bundlephobia.com/result?p=react-scroll-locky@1.1.3 reports size of 3.4kb, with 60% consumed by underlaying react-locky.

**Pull request merged**
